appengine/cq_stats/build_annotations/urls.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Url disptacher for the build_annotations app."""

from __future__ import print_function

from django.conf import urls

from build_annotations import views


urlpatterns = urls.patterns(
    '',
    urls.url(r'^$', views.ListBuildsView.as_view(),
             name='builds_list'),
    urls.url(r'edit_annotations/(?P<build_id>\d+)/$',
             views.EditAnnotationsView.as_view(),
             name='edit_annotations'))

appengine/cq_stats/cq_stats/urls.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""The main url dispatcher for this project."""

from __future__ import print_function

from django import http
from django.conf import urls


# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = urls.patterns(
    '',
    urls.url(r'^$', lambda r: http.HttpResponseRedirect('build_annotations/')),
    urls.url(r'^build_annotations/', urls.include(
        'build_annotations.urls',
        namespace='build_annotations')))

appengine/cq_stats/build_annotations/models.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Django models for cidb tables."""

from __future__ import print_function

from django.db import models
from django.core import exceptions as django_exceptions

from build_annotations import fields as ba_fields


class BaseModel(models.Model):
  """Abstract base class to store all app-wide Meta options."""

  class Meta(object):
    """Set meta options for all models in this module."""
    # This property not inherited.
    abstract = True

    # The schema for CIDB is maintained external to this app.
    managed = False
    # Allow us to split the models.py file into different modules.
    app_label = 'cq_stats_sheet'
    # Each model should explicitly set this option. The default django model to
    # table name mapping does not work for us.
    db_table = 'Please define me'

  def __iter__(self):
    for field_name in self._meta.get_all_field_names():
      value = None
      if hasattr(self, field_name):
        value = getattr(self, field_name)
      yield field_name, value

  def __unicode__(self):
    result = []
    for _, value in self:
      result.append(unicode(value))
    return u', '.join(result)

  def __str__(self):
    return str(unicode(self))


class UpdateAwareMixIn(object):
  """MixIn to optimize database writes by tracking when a model has changed.

  This MixIn adds a |_dirty| bit that is duly updated on object updates and
  short-circuits save for objects that are known to be fresh.
  """

  # These fields do not contribute towards dirty-ness of a row.
  # A 'last_updated' field is an example of fields to ignore.
  IGNORE_FIELDS = []

  def __init__(self, *args, **kwargs):
    super(UpdateAwareMixIn, self).__init__(*args, **kwargs)
    # Clear the dirty bit *after* initialization.
    # The semantics are that any fields initialized through the constructor do
    # not dirty the object.
    self._dirty = False

  @property
  def dirty(self):
    return self._dirty

  def __setattr__(self, key, value):
    # Special case any attributes that might be set in the method body below.
    if key == '_dirty' or key in self.IGNORE_FIELDS:
      return super(UpdateAwareMixIn, self).__setattr__(key, value)

    try:
      old_value = getattr(self, key)
      if old_value != value:
        self._dirty = True
    except (AttributeError, django_exceptions.ObjectDoesNotExist):
      self._dirty = True
    return super(UpdateAwareMixIn, self).__setattr__(key, value)

  def save(self, *args, **kwargs):
    if not self._dirty:
      return

    super(UpdateAwareMixIn, self).save(*args, **kwargs)
    self._dirty = False


class BuildTable(BaseModel):
  """Model for cidb.buildTable."""

  class Meta(object):
    """Set extra table options."""
    db_table = 'buildTable'

  id = ba_fields.ReadOnlyIntegerField(primary_key=True)
  last_updated = ba_fields.ReadOnlyDateTimeField()
  master_build_id = ba_fields.ReadOnlyForeignKey('self',
                                                 db_column='master_build_id')
  buildbot_generation = ba_fields.ReadOnlyIntegerField()
  waterfall = ba_fields.ReadOnlyCharField()
  build_number = ba_fields.ReadOnlyIntegerField()
  bot_hostname = ba_fields.ReadOnlyCharField()
  start_time = ba_fields.ReadOnlyDateTimeField()
  finish_time = ba_fields.ReadOnlyDateTimeField()
  status = ba_fields.ReadOnlyCharField()
  status_pickle = ba_fields.ReadOnlyBlobField()
  build_type = ba_fields.ReadOnlyCharField()
  chrome_version = ba_fields.ReadOnlyCharField()
  milestone_version = ba_fields.ReadOnlyCharField()
  platform_version = ba_fields.ReadOnlyCharField()
  full_version = ba_fields.ReadOnlyCharField()
  sdk_version = ba_fields.ReadOnlyCharField()
  toolchain_url = ba_fields.ReadOnlyURLField()
  final = ba_fields.ReadOnlyBooleanField()
  metadata_url = ba_fields.ReadOnlyURLField()
  summary = ba_fields.ReadOnlyCharField()
  deadline = ba_fields.ReadOnlyDateTimeField()


class BuildStageTable(BaseModel):
  """Model for cidb.buildStageTable."""

  class Meta(object):
    """Set extra table options."""
    db_table = 'buildStageTable'

  # Not used directly in field definition for readonly tables, but used
  # elsewhere as constants.
  FAIL = 'fail'
  PASS = 'pass'
  INFLIGHT = 'inflight'
  MISSING = 'missing'
  PLANNED = 'planned'
  SKIPPED = 'skipped'
  FORGIVEN = 'forgiven'
  STATUS_CHOICES = (
      (FAIL, 'Stage failed'),
      (PASS, 'Stage passed! Hurray!'),
      (INFLIGHT, 'Stage is inflight'),
      (MISSING, 'Status missing'),
      (PLANNED, 'Stage is planned'),
      (SKIPPED, 'Stage skipped'),
      (FORGIVEN, 'Stage failed but forgiven'))

  id = ba_fields.ReadOnlyIntegerField(primary_key=True)
  build_id = ba_fields.ReadOnlyForeignKey('BuildTable',
                                          db_column='build_id')
  name = ba_fields.ReadOnlyCharField()
  board = ba_fields.ReadOnlyCharField()
  status = ba_fields.ReadOnlyEnumField()
  last_updated = ba_fields.ReadOnlyDateTimeField()
  start_time = ba_fields.ReadOnlyDateTimeField()
  finish_time = ba_fields.ReadOnlyDateTimeField()
  final = ba_fields.ReadOnlyBooleanField()


class ClActionTable(BaseModel):
  """Model for cidb.clActionTable."""

  class Meta(object):
    """Set extra table options."""
    db_table = 'clActionTable'

  # Not used directly in field definition for readonly tables, but used
  # elsewhere as constants.
  PICKED_UP = 'picked_up'
  SUBMITTED = 'submitted'
  KICKED_OUT = 'kicked_out'
  SUBMIT_FAILED = 'submit_failed'
  VERIFIED = 'verified'
  FORGIVEN = 'forgiven'
  # This list of choices is not exhaustive yet. It's only enough for CQ stats.
  ACTION_CHOICES = (
      (PICKED_UP, 'CL picked up by CQ'),
      (SUBMITTED, 'CL submitted by CQ'),
      (KICKED_OUT, 'CL kicked out by CQ'),
      (SUBMIT_FAILED, 'CQ failed to submit CL'),
      (VERIFIED, 'CL verified by CQ'),
      (FORGIVEN, 'CQ run failed, but CL forgiven'))

  id = ba_fields.ReadOnlyIntegerField(primary_key=True)
  build_id = ba_fields.ReadOnlyForeignKey('BuildTable',
                                          db_column='build_id')
  change_number = ba_fields.ReadOnlyIntegerField()
  patch_number = ba_fields.ReadOnlyIntegerField()
  change_source = ba_fields.ReadOnlyEnumField()
  action = ba_fields.ReadOnlyEnumField()
  reason = ba_fields.ReadOnlyCharField()
  timestamp = ba_fields.ReadOnlyDateTimeField()


class FailureTable(BaseModel):
  """Model for cidb.failureTable."""

  class Meta(object):
    """Set extra table options."""
    db_table = 'failureTable'

  id = ba_fields.ReadOnlyIntegerField(primary_key=True)
  build_stage_id = ba_fields.ReadOnlyForeignKey('BuildStageTable',
                                                db_column='build_stage_id')
  outer_failure_id = ba_fields.ReadOnlyForeignKey('self',
                                                  db_column='outer_failure_id')
  exception_type = ba_fields.ReadOnlyCharField()
  exception_message = ba_fields.ReadOnlyCharField()
  exception_category = ba_fields.ReadOnlyEnumField()
  extra_info = ba_fields.ReadOnlyCharField()
  timestamp = ba_fields.ReadOnlyDateTimeField()


# The order of inheritence is significant.
# UpdateAwareMixIn must preceed the django model.Model subclass.
class AnnotationsTable(UpdateAwareMixIn, BaseModel):
  """Model for cidb.annotationsTable."""

  class Meta(object):
    """Set extra table options."""
    db_table = 'annotationsTable'

  # For UpdateAwareMixIn
  IGNORE_FIELDS = ['last_updated']

  BAD_CL = 'bad_cl'
  BUG_IN_TOT = 'bug_in_tot'
  MERGE_CONFLICT = 'merge_conflict'
  TREE_CONFLICT = 'tree_conflict'
  SCHEDULED_ABORT = 'scheduled_abort'
  CL_NOT_READY = 'cl_not_ready'
  BAD_CHROME = 'bad_chrome'
  TEST_FLAKE = 'test_flake'
  GERRIT_FAILURE = 'gerrit_failure'
  GS_FAILURE = 'gs_failure'
  LAB_FAILURE = 'lab_failure'
  BAD_BINARY_FAILURE = 'bad_binary_failure'
  BUILD_FLAKE = 'build_flake'
  INFRA_FAILURE = 'infra_failure'
  MYSTERY = 'mystery'
  FAILURE_CATEGORY_CHOICES = (
      (BAD_CL, 'Bad CL (Please specify CL)'),
      (BUG_IN_TOT, 'Bug in ToT (Please specify bug)'),
      (MERGE_CONFLICT, 'Merge conflict'),
      (TREE_CONFLICT, 'Tree conflict'),
      (SCHEDULED_ABORT, 'Scheduled Abort'),
      (CL_NOT_READY, 'CL was marked not ready (Please specify CL)'),
      (BAD_CHROME, 'Bad chrome (Please speficy bug)'),
      (TEST_FLAKE, 'Test flake'),
      (GERRIT_FAILURE, 'Gerrit failure'),
      (GS_FAILURE, 'Google Storage failure'),
      (LAB_FAILURE, 'Lab failure'),
      (BAD_BINARY_FAILURE, 'Bad binary packages'),
      (BUILD_FLAKE, 'Local build flake'),
      (INFRA_FAILURE, 'Other Infrastructure failure'),
      (MYSTERY, 'Unknown failure: MyStErY'))

  # Warning: Some field constraints are duplicated here from the database
  # schema in CIDB.
  id = models.AutoField(primary_key=True)
  build_id = models.ForeignKey('BuildTable', db_column='build_id')
  last_updated = models.DateTimeField(auto_now=True)
  last_annotator = models.CharField(max_length=80)
  failure_category = models.CharField(
      max_length=max(len(x) for x, y in FAILURE_CATEGORY_CHOICES),
      choices=FAILURE_CATEGORY_CHOICES,
      default='mystery')
  failure_message = models.CharField(max_length=1024, blank=True, null=True)
  blame_url = models.CharField(max_length=80, blank=True, null=True)
  notes = models.CharField(max_length=1024, blank=True, null=True)

appengine/cq_stats/build_annotations/forms.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Forms used by the build_annotations app."""

from __future__ import print_function

from django import forms

from build_annotations import models as ba_models


class SearchForm(forms.Form):
  """Form to limit builds shown on the landing page."""
  latest_build_id = forms.IntegerField()
  num_builds = forms.IntegerField(label='Number of results')


class AnnotationsForm(forms.ModelForm):
  """Form to add/edit a single annotation to a build."""

  # pylint: disable=no-init, old-style-class
  class Meta:
    """Set meta options for the form."""
    model = ba_models.AnnotationsTable
    fields = ['failure_category', 'failure_message', 'blame_url', 'notes']


AnnotationsFormSet = forms.models.modelformset_factory(
    ba_models.AnnotationsTable,
    form=AnnotationsForm,
    can_delete=True)

appengine/cq_stats/build_annotations/views.py
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""All django views for the build_annotations app."""

from __future__ import print_function

from django import http
from django import shortcuts
from django.core import urlresolvers
from django.views import generic

from build_annotations import build_row_controller
from build_annotations import models as ba_models
from build_annotations import forms as ba_forms


class ListBuildsView(generic.list.ListView):
  """The landing page view of the app. Lists requested builds."""

  template_name = 'build_annotations/index.html'

  def __init__(self, *args, **kwargs):
    super(ListBuildsView, self).__init__(*args, **kwargs)
    self._search_form = None
    self._controller = None
    self._session = None

  def get_queryset(self):
    self._EnsureSessionInitialized()
    self._controller = build_row_controller.BuildRowController()
    return self._controller.GetStructuredBuilds(
        latest_build_id=self._session['latest_build_id'],
        num_builds=self._session['num_builds'])

  def get_context_object_name(self, _):
    return 'builds_list'

  def get_context_data(self, **kwargs):
    context = super(ListBuildsView, self).get_context_data(**kwargs)
    context['search_form'] = self._GetSearchForm()
    context['latest_build_id_cached'] = self._GetLatestBuildId()
    return context

  def get(self, request):
    self._session = request.session
    return super(ListBuildsView, self).get(request)

  def post(self, request):
    self._session = request.session
    form = ba_forms.SearchForm(request.POST)
    self._search_form = form
    if form.is_valid():
      self._session['latest_build_id'] = form.cleaned_data['latest_build_id']
      self._session['num_builds'] = form.cleaned_data['num_builds']
    return self.get(request)

  def put(self, *args, **kwargs):
    return self.post(*args, **kwargs)

  def _GetSearchForm(self):
    if self._search_form is not None:
      return self._search_form
    return ba_forms.SearchForm(
        {'latest_build_id': self._session['latest_build_id'],
         'num_builds': self._session['num_builds']})

  def _EnsureSessionInitialized(self):
    latest_build_id = self._session.get('latest_build_id', None)
    num_results = self._session.get('num_builds', None)
    if latest_build_id is None or num_results is None:
      # We don't have a valid search history in this session, obtain defaults.
      controller = build_row_controller.BuildRowController()
      controller.GetStructuredBuilds(num_builds=1)
      self._session['latest_build_id'] = controller.latest_build_id
      self._session['num_builds'] = controller.DEFAULT_NUM_BUILDS

  def _GetLatestBuildId(self):
    controller = build_row_controller.BuildRowController()
    controller.GetStructuredBuilds(num_builds=1)
    return controller.latest_build_id


class EditAnnotationsView(generic.base.View):
  """View that handles annotation editing page."""

  template_name = 'build_annotations/edit_annotations.html'

  def __init__(self, *args, **kwargs):
    self._formset = None
    self._annotator = 'default_annotator'
    self._context = {}
    self._request = None
    self._session = None
    self._build_id = None
    super(EditAnnotationsView, self).__init__(*args, **kwargs)

  def get(self, request, build_id):
    self._request = request
    self._build_id = build_id
    self._session = request.session
    self._PopulateContext()
    return shortcuts.render(request, self.template_name, self._context)

  def post(self, request, build_id):
    self._request = request
    self._build_id = build_id
    self._session = request.session
    self._formset = ba_forms.AnnotationsFormSet(request.POST)
    if self._formset.is_valid():
      self._SaveAnnotations()
      return http.HttpResponseRedirect(
          urlresolvers.reverse('build_annotations:edit_annotations',
                               args=[self._build_id]))
    else:
      self._PopulateContext()
      return shortcuts.render(request, self.template_name, self._context)

  def _PopulateContext(self):
    build_row = self._GetBuildRow()
    if build_row is None:
      raise http.Http404

    self._context = {}
    self._context['build_row'] = build_row
    self._context['annotations_formset'] = self._GetAnnotationsFormSet()

  def _GetBuildRow(self):
    controller = build_row_controller.BuildRowController()
    build_row_list = controller.GetStructuredBuilds(
        latest_build_id=self._build_id,
        num_builds=1)
    if not build_row_list:
      return None
    return build_row_list[0]

  def _GetAnnotationsFormSet(self):
    if self._formset is None:
      build_row = self._GetBuildRow()
      if build_row is not None:
        queryset = build_row.annotations
      else:
        queryset = ba_models.AnnotationsTable.objects.none()
      self._formset = ba_forms.AnnotationsFormSet(queryset=queryset)
    return self._formset

  def _SaveAnnotations(self):
    models_to_save = self._formset.save(commit=False)
    build_row = self._GetBuildRow()
    for model in models_to_save:
      if not hasattr(model, 'build_id') or model.build_id is None:
        model.build_id = build_row.build_entry
        model.last_annotator = self._annotator
      model.save()

appengine/cq_stats/build_annotations/templates/build_annotations/edit_annotations.html
<html>
<head>
{% load build_annotations_filters %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'build_annotations/base.css' %}"/>
<script type="text/javascript" src="{% static 'build_annotations/base.js' %}"></script>
</head>

<body>
<div>
  <a href="{% url 'build_annotations:builds_list' %}">Builds List</a>
</div>
<h1>Annotate build {{ build_row.id }}</h1>

<table class="build_details">
  <tr>
    <th class="build_details">Build Number</th>
    <td class="build_details">{{ build_row.build_number }}</td>
  </tr>
  <tr>
    <th class="build_details">Status</th>
    <td class="build_details">{{ build_row.status }}</td>
  </tr>
  <tr>
    <th class="build_details">Summary</th>
    <td class="build_details">{{ build_row.summary|linebreaksbr }}</td>
  </tr>
  <tr>
    <th class="build_details">Start Time</th>
    <td class="build_details">{{ build_row.start_time }}</td>
  </tr>
  <tr>
    <th class="build_details">Runtime</th>
    <td class="build_details">{{ build_row.run_time }}</td>
  </tr>
  <tr>
    <th class="build_details">Weekday</th>
    <td class="build_details">{{ build_row.weekday }}</td>
  </tr>
  <tr>
    <th class="build_details">ChromeOS Version</th>
    <td class="build_details">{{ build_row.chromeos_version }}</td>
  </tr>
  <tr>
    <th class="build_details">Chrome Version</th>
    <td class="build_details">{{ build_row.chrome_version }}</td>
  </tr>
  <tr>
    <th class="build_details">Failed Stages</th>
    <td class="build_details">{{ build_row.failed_stages }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Picked Up</th>
    <td class="build_details">{{ build_row.picked_up_count }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Submitted</th>
    <td class="build_details">{{ build_row.submitted_count }}</td>
  </tr>
  <tr>
    <th class="build_details">CLs Kicked Out</th>
    <td class="build_details">{{ build_row.kicked_out_count }}</td>
  </tr>
</table>
<form action="{% url 'build_annotations:edit_annotations' build_row.id %}"
      method="post">
  {% csrf_token %}
  {{ annotations_formset.management_form }}
  <table class="annotations_list">
    <tr>
    {% for form in annotations_formset %}
      {% if forloop.first %}
        <tr>
          <th class="annotations_list">Failure Category</th>
          <th class="annotations_list">Failure Message</th>
          <th class="annotations_list">Blame URL</th>
          <th class="annotations_list">Notes</th>
          <th class="annotations_list">Update</th>
        </tr>
      {% endif %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% if not forloop.last %}
        <tr id="annotation_{{ forloop.counter }}_noedit">
          <td>{{ form.failure_category.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.failure_message.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.blame_url.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td>{{ form.notes.value|default_if_none:""|striptags|crosurlize|linebreaks }}</td>
          <td><a href="javascript:void(0)" onclick="editAnnotation('{{ forloop.counter }}')">edit</a>
        </tr>
      {% endif %}

      {% if not forloop.last %}
        <tr id="annotation_{{ forloop.counter }}_edit" class="hidden">
      {% else %}
        <tr id="annotation_{{ forloop.counter }}_edit">
      {% endif %}
            <td class="annotations_list">{{ form.failure_category }}<br><div class="errorlist">{{ form.failure_category.errors }}</div></td>
            <td class="annotations_list">{{ form.failure_message }}<br><div class="errorlist">{{ form.failure_message.errors }}</div></td>
            <td class="annotations_list">{{ form.blame_url }}<br><div class="errorlist">{{ form.blame_url.errors }}</div></td>
            <td class="annotations_list">{{ form.notes }}<br><div class="errorlist">{{ form.notes.errors }}</div></td>
            <td class="annotations_list"><label>Mark for deletion: </label>{{ form.DELETE }}</td>
            <td class="annotations_list">{{ form. }}<br><div class="errorlist">{{ form..errors }}</div></td>
        </tr>
    {% endfor %}
  </table>
  <input type="submit" value="Save Changes"/>
</form>

</body>
</html>

appengine/cq_stats/build_annotations/templates/build_annotations/index.html
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'build_annotations/base.css' %}"/>
<script type="text/javascript" src="{% static 'build_annotations/base.js' %}"></script>
</head>

<body>
<h1>Builds List</h1>
<form action="{% url 'build_annotations:builds_list' %}" method="post">
  {% csrf_token %}
  <table>
    <tr>
      <th><label>{{ search_form.latest_build_id.label }}</label></th>
      <td>{{ search_form.latest_build_id }}</td>
      <td>
        <button type="button" onclick="populateLatest()">Get latest</button>
        <input type="hidden" id="latest_build_id_cached" value="{{ latest_build_id_cached }}"/>
      </td>
      <td class="error_message">{{ search_form.latest_build_id.errors }}</td>
    </tr>
    <tr>
      <th><label>{{ search_form.num_builds.label }}</label></th>
      <td>{{ search_form.num_builds }}</td>
      <td class="error_message">{{ search_form.num_builds.errors }}</td>
    </tr>
  </table>
  <input type="submit" value="Update List"/>
</form>

<table class="build_list">
  <tr>
    <th class="build_list">Build ID</th>
    <th class="build_list">Build Number</th>
    <th class="build_list">Status</th>
    <th class="build_list">Summary</th>
    <th class="build_list">Start Time</th>
    <th class="build_list">Runtime</th>
    <th class="build_list">Weekday?</th>
    <th class="build_list">Annotation Summary</th>
  </tr>
{% for build_row in builds_list %}
  <tr>
    <td class="build_list"><a href="{% url 'build_annotations:edit_annotations' build_row.id %}">{{ build_row.id }}</a></td>
    <td class="build_list">{{ build_row.build_number }}</td>
    <td class="build_list">{{ build_row.status|truncatechars:20 }}</td>
    <td class="build_list">{{ build_row.summary|truncatechars:50|cut:'\n\r' }}</td>
    <td class="build_list">{{ build_row.start_time|date }}</td>
    <td class="build_list">{{ build_row.run_time|time }}</td>
    <td class="build_list">{{ build_row.weekday|yesno }}</td>
    <td class="build_list">{{ build_row.annotation_summary|truncatechars:150 }}</td>
  </tr>
{% endfor %}
</table>

</body>
</html>